# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

raw_output = ""
user_token = ""

[filter]
  limit = ""
  offset = ""
  topic = ""

[remotes]
  bootstrap_url = "http://localhost:9013"
  certs_url = "http://localhost:9019"
  http_adapter_url = "http://localhost/http"
  reader_url = "http://localhost:9009"
  things_url = "http://localhost:9000"
  tls_verification = false
  users_url = "http://localhost:9002"
