# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This file is used to configure NATS broker.
# It used when running nats both as an MQTT and Message broker.
services:
  nats:
    extends:
      file: ../nats.yml
      service: broker
    container_name: magistrala-nats
    restart: on-failure
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-broker-volume:/data
    profiles:
      - nats_nats
      - nats_rabbitmq
