# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This file configures Magistrala brokers. Magistrala uses two types of brokers:
# 1. MQTT_BROKER: Handles MQTT communication between MQTT adapters and message broker.
# 2. MESSAGE_BROKER: Manages communication between adapters and Magistrala writer services.
#
# MQTT_BROKER can be either 'vernemq' or 'nats'.
# MESSAGE_BROKER can be either 'nats' or 'rabbitmq'.
#
# Each broker has a unique profile for configuration. The available profiles are:
# - vernemq_nats: Uses 'vernemq' as MQTT_BROKER and 'nats' as MESSAGE_BROKER.
# - vernemq_rabbitmq: Uses 'vernemq' as MQTT_BROKER and 'rabbitmq' as MESSAGE_BROKER.
# - nats_nats: Uses 'nats' as both MQTT_BROKER and MESSAGE_BROKER.
# - nats_rabbitmq: Uses 'nats' as MQTT_BROKER and 'rabbitmq' as MESSAGE_BROKER.
#

include:
  - path: profiles/nats.yml
    env_file: docker/.env

services:
  vernemq:
    image: magistrala/vernemq:${MG_RELEASE_TAG}
    container_name: magistrala-vernemq
    restart: on-failure
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: ${MG_DOCKER_VERNEMQ_ALLOW_ANONYMOUS}
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: ${MG_DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL}
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-mqtt-broker-volume:/var/lib/vernemq
    profiles:
      - vernemq_nats
      - vernemq_rabbitmq

  broker:
    extends:
      file: nats.yml
      service: broker
    container_name: magistrala-broker
    restart: on-failure
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-broker-volume:/data
    profiles:
      - vernemq_nats
      - vernemq_rabbitmq
      - nats_rabbitmq
