# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

services:
  broker:
    image: nats:2.9.21-alpine
    command: "--config=/etc/nats/nats.conf"
    volumes:
      - ./../nats/:/etc/nats
    environment:
      - MG_NATS_PORT=${MG_NATS_PORT}
      - MG_NATS_HTTP_PORT=${MG_NATS_HTTP_PORT}
      - MG_NATS_JETSTREAM_KEY=${MG_NATS_JETSTREAM_KEY}
    ports:
      - ${MG_NATS_PORT}:${MG_NATS_PORT}
      - ${MG_NATS_HTTP_PORT}:${MG_NATS_HTTP_PORT}
