# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

volumes:
  magistrala-es-redis-volume:

services:
  es-redis:
    image: redis:7.2.0-alpine
    container_name: magistrala-es-redis
    restart: on-failure
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-es-volume:/data
    profiles:
      - redis
