# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

FROM scratch
ARG SVC
COPY magistrala-$SVC /exe
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/exe"]
