# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional InfluxDB and InfluxDB-writer services
# for the Magistrala platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

version: "3.7"

networks:
  magistrala-base-net:

volumes:
  magistrala-smpp-notifier-volume:

services:
  smpp-notifier-db:
    image: postgres:10.2-alpine
    container_name: magistrala-smpp-notifier-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${MG_SMPP_NOTIFIER_DB_USER}
      POSTGRES_PASSWORD: ${MG_SMPP_NOTIFIER_DB_PASS}
      POSTGRES_DB: ${MG_SMPP_NOTIFIER_DB_NAME}
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-smpp-notifier-volume:/var/lib/postgresql/datab

  smpp-notifier:
    image: magistrala/smpp-notifier:latest
    container_name: magistrala-smpp-notifier
    depends_on:
      - smpp-notifier-db
    restart: on-failure
    environment:
      MG_SMPP_NOTIFIER_LOG_LEVEL: ${MG_SMPP_NOTIFIER_LOG_LEVEL}
      MG_SMPP_NOTIFIER_FROM_ADDR: ${MG_SMPP_NOTIFIER_FROM_ADDR}]
      MG_SMPP_NOTIFIER_CONFIG_PATH: ${MG_SMPP_NOTIFIER_CONFIG_PATH}
      MG_SMPP_NOTIFIER_HTTP_HOST: ${MG_SMPP_NOTIFIER_HTTP_HOST}
      MG_SMPP_NOTIFIER_HTTP_PORT: ${MG_SMPP_NOTIFIER_HTTP_PORT}
      MG_SMPP_NOTIFIER_HTTP_SERVER_CERT: ${MG_SMPP_NOTIFIER_HTTP_SERVER_CERT}
      MG_SMPP_NOTIFIER_HTTP_SERVER_KEY: ${MG_SMPP_NOTIFIER_HTTP_SERVER_KEY}
      MG_SMPP_NOTIFIER_DB_HOST: ${MG_SMPP_NOTIFIER_DB_HOST}
      MG_SMPP_NOTIFIER_DB_PORT: ${MG_SMPP_NOTIFIER_DB_PORT}
      MG_SMPP_NOTIFIER_DB_USER: ${MG_SMPP_NOTIFIER_DB_USER}
      MG_SMPP_NOTIFIER_DB_PASS: ${MG_SMPP_NOTIFIER_DB_PASS}
      MG_SMPP_NOTIFIER_DB_NAME: ${MG_SMPP_NOTIFIER_DB_NAME}
      MG_SMPP_NOTIFIER_DB_SSL_MODE: ${MG_SMPP_NOTIFIER_DB_SSL_MODE}
      MG_SMPP_NOTIFIER_DB_SSL_CERT: ${MG_SMPP_NOTIFIER_DB_SSL_CERT}
      MG_SMPP_NOTIFIER_DB_SSL_KEY: ${MG_SMPP_NOTIFIER_DB_SSL_KEY}
      MG_SMPP_NOTIFIER_DB_SSL_ROOT_CERT: ${MG_SMPP_NOTIFIER_DB_SSL_ROOT_CERT}
      MG_SMPP_ADDRESS: ${MG_SMPP_ADDRESS}
      MG_SMPP_USERNAME: ${MG_SMPP_USERNAME}
      MG_SMPP_PASSWORD: ${MG_SMPP_PASSWORD}
      MG_SMPP_SYSTEM_TYPE: ${MG_SMPP_SYSTEM_TYPE}
      MG_SMPP_SRC_ADDR_TON: ${MG_SMPP_SRC_ADDR_TON}
      MG_SMPP_SRC_ADDR_NPI: ${MG_SMPP_SRC_ADDR_NPI}
      MG_SMPP_DST_ADDR_TON: ${MG_SMPP_DST_ADDR_TON}
      MG_SMPP_DST_ADDR_NPI: ${MG_SMPP_DST_ADDR_NPI}
      MG_AUTH_GRPC_URL: ${MG_AUTH_GRPC_URL}
      MG_AUTH_GRPC_TIMEOUT: ${MG_AUTH_GRPC_TIMEOUT}
      MG_AUTH_GRPC_CLIENT_CERT: ${MG_AUTH_GRPC_CLIENT_CERT:+/auth-grpc-client.crt}
      MG_AUTH_GRPC_CLIENT_KEY: ${MG_AUTH_GRPC_CLIENT_KEY:+/auth-grpc-client.key}
      MG_AUTH_GRPC_SERVER_CA_CERTS: ${MG_AUTH_GRPC_SERVER_CA_CERTS:+/auth-grpc-server-ca.crt}
      MG_MESSAGE_BROKER_URL: ${MG_MESSAGE_BROKER_URL}
      MG_JAEGER_URL: ${MG_JAEGER_URL}
      MG_JAEGER_TRACE_RATIO: ${MG_JAEGER_TRACE_RATIO}
      MG_SEND_TELEMETRY: ${MG_SEND_TELEMETRY}
      MG_SMPP_NOTIFIER_INSTANCE_ID: ${MG_SMPP_NOTIFIER_INSTANCE_ID}
    ports:
      - ${MG_SMPP_NOTIFIER_HTTP_PORT}:${MG_SMPP_NOTIFIER_HTTP_PORT}
    networks:
      - magistrala-base-net
    volumes:
      - ./config.toml:/config.toml
      # Auth gRPC client certificates
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_CLIENT_CERT:-./ssl/certs/dummy/client_cert}
        target: /auth-grpc-client${MG_AUTH_GRPC_CLIENT_CERT:+.crt}
        bind:
          create_host_path: true
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_CLIENT_KEY:-./ssl/certs/dummy/client_key}
        target: /auth-grpc-client${MG_AUTH_GRPC_CLIENT_KEY:+.key}
        bind:
          create_host_path: true
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_SERVER_CA_CERTS:-./ssl/certs/dummy/server_ca}
        target: /auth-grpc-server-ca${MG_AUTH_GRPC_SERVER_CA_CERTS:+.crt}
        bind:
          create_host_path: true
