# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional InfluxDB and InfluxDB-writer services
# for the Magistrala platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

version: "3.7"

networks:
  magistrala-base-net:

volumes:
  magistrala-smtp-notifier-volume:

services:
  smtp-notifier-db:
    image: postgres:10.2-alpine
    container_name: magistrala-smtp-notifier-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${MG_SMTP_NOTIFIER_DB_USER}
      POSTGRES_PASSWORD: ${MG_SMTP_NOTIFIER_DB_PASS}
      POSTGRES_DB: ${MG_SMTP_NOTIFIER_DB_NAME}
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-smtp-notifier-volume:/var/lib/postgresql/datab

  smtp-notifier:
    image: magistrala/smtp-notifier:latest
    container_name: magistrala-smtp-notifier
    depends_on:
      - smtp-notifier-db
    restart: on-failure
    environment:
      MG_SMTP_NOTIFIER_LOG_LEVEL: ${MG_SMTP_NOTIFIER_LOG_LEVEL}
      MG_SMTP_NOTIFIER_FROM_ADDR: ${MG_SMTP_NOTIFIER_FROM_ADDR}]
      MG_SMTP_NOTIFIER_CONFIG_PATH: ${MG_SMTP_NOTIFIER_CONFIG_PATH}
      MG_SMTP_NOTIFIER_HTTP_HOST: ${MG_SMTP_NOTIFIER_HTTP_HOST}
      MG_SMTP_NOTIFIER_HTTP_PORT: ${MG_SMTP_NOTIFIER_HTTP_PORT}
      MG_SMTP_NOTIFIER_HTTP_SERVER_CERT: ${MG_SMTP_NOTIFIER_HTTP_SERVER_CERT}
      MG_SMTP_NOTIFIER_HTTP_SERVER_KEY: ${MG_SMTP_NOTIFIER_HTTP_SERVER_KEY}
      MG_SMTP_NOTIFIER_DB_HOST: ${MG_SMTP_NOTIFIER_DB_HOST}
      MG_SMTP_NOTIFIER_DB_PORT: ${MG_SMTP_NOTIFIER_DB_PORT}
      MG_SMTP_NOTIFIER_DB_USER: ${MG_SMTP_NOTIFIER_DB_USER}
      MG_SMTP_NOTIFIER_DB_PASS: ${MG_SMTP_NOTIFIER_DB_PASS}
      MG_SMTP_NOTIFIER_DB_NAME: ${MG_SMTP_NOTIFIER_DB_NAME}
      MG_SMTP_NOTIFIER_DB_SSL_MODE: ${MG_SMTP_NOTIFIER_DB_SSL_MODE}
      MG_SMTP_NOTIFIER_DB_SSL_CERT: ${MG_SMTP_NOTIFIER_DB_SSL_CERT}
      MG_SMTP_NOTIFIER_DB_SSL_KEY: ${MG_SMTP_NOTIFIER_DB_SSL_KEY}
      MG_SMTP_NOTIFIER_DB_SSL_ROOT_CERT: ${MG_SMTP_NOTIFIER_DB_SSL_ROOT_CERT}
      MG_AUTH_GRPC_URL: ${MG_AUTH_GRPC_URL}
      MG_AUTH_GRPC_TIMEOUT: ${MG_AUTH_GRPC_TIMEOUT}
      MG_AUTH_GRPC_CLIENT_CERT: ${MG_AUTH_GRPC_CLIENT_CERT:+/auth-grpc-client.crt}
      MG_AUTH_GRPC_CLIENT_KEY: ${MG_AUTH_GRPC_CLIENT_KEY:+/auth-grpc-client.key}
      MG_AUTH_GRPC_SERVER_CA_CERTS: ${MG_AUTH_GRPC_SERVER_CA_CERTS:+/auth-grpc-server-ca.crt}
      MG_EMAIL_USERNAME: ${MG_EMAIL_USERNAME}
      MG_EMAIL_PASSWORD: ${MG_EMAIL_PASSWORD}
      MG_EMAIL_HOST: ${MG_EMAIL_HOST}
      MG_EMAIL_PORT: ${MG_EMAIL_PORT}
      MG_EMAIL_FROM_ADDRESS: ${MG_EMAIL_FROM_ADDRESS}
      MG_EMAIL_FROM_NAME: ${MG_EMAIL_FROM_NAME}
      MG_EMAIL_TEMPLATE: ${MG_SMTP_NOTIFIER_EMAIL_TEMPLATE}
      MG_MESSAGE_BROKER_URL: ${MG_MESSAGE_BROKER_URL}
      MG_JAEGER_URL: ${MG_JAEGER_URL}
      MG_JAEGER_TRACE_RATIO: ${MG_JAEGER_TRACE_RATIO}
      MG_SEND_TELEMETRY: ${MG_SEND_TELEMETRY}
      MG_SMTP_NOTIFIER_INSTANCE_ID: ${MG_SMTP_NOTIFIER_INSTANCE_ID}
    ports:
      - ${MG_SMTP_NOTIFIER_HTTP_PORT}:${MG_SMTP_NOTIFIER_HTTP_PORT}
    networks:
      - magistrala-base-net
    volumes:
      - ./config.toml:/config.toml
      - ../../templates/${MG_SMTP_NOTIFIER_EMAIL_TEMPLATE}:/${MG_SMTP_NOTIFIER_EMAIL_TEMPLATE}
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_CLIENT_CERT:-./ssl/certs/dummy/client_cert}
        target: /auth-grpc-client${MG_AUTH_GRPC_CLIENT_CERT:+.crt}
        bind:
          create_host_path: true
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_CLIENT_KEY:-./ssl/certs/dummy/client_key}
        target: /auth-grpc-client${MG_AUTH_GRPC_CLIENT_KEY:+.key}
        bind:
          create_host_path: true
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_SERVER_CA_CERTS:-./ssl/certs/dummy/server_ca}
        target: /auth-grpc-server-ca${MG_AUTH_GRPC_SERVER_CA_CERTS:+.crt}
        bind:
          create_host_path: true
