# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    strategy:
      matrix:
        service: [users, things, coap, http, mqtt, ws, certs, provision, cli, lora, opcua, logger, tools, internal, pkg, readers, consumers, twins, bootstrap]

    uses: ./.github/workflows/test.yml
    secrets: inherit 
    with:
      service: ${{ matrix.service }}
