# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  swagger-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Swagger UI action
        id: swagger-ui-action
        uses: blokovi/swagger-ui-action@main
        with:
          dir: './api/openapi'
          pattern: '*.yml'
          debug: 'true'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
          cname: api.mainflux.io

